# Generated by Django 5.1.3 on 2024-11-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0002_cita'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
