# Generated by Django 5.1.3 on 2024-11-27 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoria',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 27, 15, 37, 5, 75967, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
