# Generated by Django 5.1.3 on 2024-11-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0005_solicitudtutoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudtutoria',
            old_name='fecha_solicitud',
            new_name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='solicitudtutoria',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=50),
        ),
    ]
