# Generated by Django 5.1.3 on 2024-12-02 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0006_rename_fecha_solicitud_solicitudtutoria_fecha_creacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoria',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='tutorias_inscritas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutoria',
            name='unidad_duracion',
            field=models.CharField(choices=[('semanas', 'Semanas'), ('dias', 'Días'), ('horas', 'Horas'), ('minutos', 'Minutos')], default='minutos', max_length=10),
        ),
        migrations.AlterField(
            model_name='tutoria',
            name='duracion',
            field=models.PositiveIntegerField(help_text='Duración numérica'),
        ),
    ]
