# Generated by Django 5.1.3 on 2024-12-02 22:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0007_tutoria_estudiantes_tutoria_unidad_duracion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoria',
            name='duracion',
            field=models.PositiveIntegerField(help_text='Duración en número'),
        ),
        migrations.AlterField(
            model_name='tutoria',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, help_text='Seleccione los estudiantes inscritos en la tutoría.', related_name='tutorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutoria',
            name='unidad_duracion',
            field=models.CharField(choices=[('min', 'Minutos'), ('hr', 'Horas'), ('day', 'Días'), ('wk', 'Semanas')], default='min', max_length=3),
        ),
    ]
