# Generated by Django 5.1.3 on 2024-12-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0008_alter_tutoria_duracion_alter_tutoria_estudiantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoria',
            name='unidad_duracion',
            field=models.CharField(choices=[('min', 'minutos'), ('hr', 'horas'), ('day', 'días'), ('wk', 'semanas')], default='min', max_length=3),
        ),
    ]
