# Generated by Django 5.1.3 on 2024-12-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0011_alter_solicitudtutoria_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtutoria',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtutoria',
            name='lugar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtutoria',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=50),
        ),
    ]
